apiVersion: 1
datasources:
- name: Graphite
  type: graphite
  access: proxy
  url: http://graphite:80
  version: 1
  editable: true

- name: InfluxDB
  type: influxdb
  access: proxy
  url: http://influxdb:8086
  database: int
  version: 1
  editable: true

- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  version: 1
  editable: true
