{
 "title": "InfluxDB INT Dashboard",
 "time": { "from": "2020-01-25T17:52:01.436Z", "to": "2020-01-25T17:53:24.439Z" },
 "panels": [
  {
   "title": "Flow Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "dst_ip" ], "type": "tag" },
      { "params": [ "dst_port" ], "type": "tag" },
      { "params": [ "src_port" ], "type": "tag" },
      { "params": [ "src_ip" ], "type": "tag" },
      { "params": [ "protocol" ], "type": "tag" }
     ],
     "measurement": "flow_latency",
     "query": "SELECT \"value\" FROM \"flow_latency\" WHERE $timeFilter GROUP BY \"dst_ip\", \"dst_port\", \"src_port\", \"src_ip\", \"protocol\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Switch Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "switch_id" ], "type": "tag" }
     ],
     "measurement": "switch_latency",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Link Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "egress_port_id" ], "type": "tag" },
      { "params": [ "egress_switch_id" ], "type": "tag" },
      { "params": [ "ingress_port_id" ], "type": "tag" },
      { "params": [ "ingress_switch_id" ], "type": "tag" }
     ],
     "measurement": "link_latency",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queue Occupancy",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "queue_id" ], "type": "tag" },
      { "params": [ "switch_id" ], "type": "tag" }
     ],
     "measurement": "queue_occupancy",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}